[package]
name = "halfred"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic ="abort"

[profile.release]
panic ="abort"

[profile.test]
panic ="abort"

[package.metadata.cortex-m-rt]
memory = "memory.x"

[features]
avr = []
arm = []
