[package]
name = "halfred"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.3"

[profile.dev]
panic ="abort"

[profile.release]
panic ="abort"

[profile.test]
panic ="abort"

[features]
avr = []
arm = []
